export default {
  id: 'evt_1Hw96LBvVBgmhQW4NgFZu0hH',
  object: 'event',
  api_version: '2020-08-27',
  created: 1607445105,
  data: {
    object: {
      id: 'pi_1Hw96KBvVBgmhQW4Bs4z54fQ',
      object: 'payment_intent',
      amount: 2000,
      amount_capturable: 0,
      amount_received: 2000,
      application: null,
      application_fee_amount: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic',
      charges: [Object],
      client_secret:
        'pi_1Hw96KBvVBgmhQW4Bs4z54fQ_secret_MWsIxxq3Io13q56KcF7Rfkyg9',
      confirmation_method: 'automatic',
      created: 1607445104,
      currency: 'usd',
      customer: null,
      description: '(created by Stripe CLI)',
      invoice: null,
      last_payment_error: null,
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: 'pm_1Hw96JBvVBgmhQW4RNKPyfkc',
      payment_method_options: [Object],
      payment_method_types: [Array],
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: [Object],
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 3,
  request: { id: 'req_5t8pzLo9wKLVoQ', idempotency_key: null },
  type: 'payment_intent.succeeded',
};
