# Validate lint, build, and tests on PR
name: help-post-comment-count Push Master

on:
  push:
    branches:
      - master
    paths:
      - "functions/help-post-comment-count/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci, run validate
        run: |
          cd functions/help-post-comment-count
          cp .env.sample .env
          npm ci
          npm run validate
      - name: Post-Build Copies
        run: |
          cd functions/help-post-comment-count
          pwd
          npm pkg delete scripts.build
          cp ./package.json __build__/
          cp ./package-lock.json __build__/
          git rev-list --count master > __build__/ccnt.txt
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tc-api
          path: functions/help-post-comment-count/__build__
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'

  deploy-function:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: tc-api
      - name: Setup google auth for github actions
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}          
      - name: Setup gcloud Actions CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '428.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: write .env file
        run: |
          gcloud secrets versions access latest --secret prod-help-post-comment-count-env > tc-api/.env
          C_CNT=$(cat tc-api/ccnt.txt)
          rm -f tc-api/ccnt.txt
          SENTRYREL=SENTRY_VERSION=help-post-comment-count@$(cat tc-api/package.json | jq '.version' | tr -d '"')-$C_CNT.$(echo $GITHUB_SHA | cut -c1-7)
          echo "" >> tc-api/.env
          echo $SENTRYREL >> tc-api/.env
          echo "SENTRYREL=$SENTRYREL" >> $GITHUB_ENV
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Checks and verifications
        run: |
          echo "**********"
          echo $SENTRYREL
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo "**********"
          echo $PWD
          ls -lasiR
      - name: Run GCP Deploy Function - help-post-comment-count
        run: |
          cd tc-api
          gcloud functions deploy help-post-comment-count --runtime nodejs18 --trigger-event providers/cloud.firestore/eventTypes/document.create --trigger-resource "projects/all-that/databases/(default)/documents/helpPosts/{helpPostId}/helpPostComments/{commentId}" --entry-point helpPostCommentCount
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
