name: that-api-ical-generator Push Master

on:
  push:
    branches:
      - master
    paths:
      - "functions/that-api-ical-generator/**"

jobs:
  build:
    name: Build that-api-ical-generator
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm ci, run validate
        run: |
          cd functions/that-api-ical-generator
          pwd
          cp .env.sample .env
          npm ci
          npm run validate
          rm .env
        env:
          CI: true
          HUSKY: 0
      - name: Post-Build Copies
        run: |
          cd functions/that-api-ical-generator
          pwd
          cp ./package.json __build__/
          cp ./package-lock.json __build__/
          cp ./Dockerfile __build__/
          git rev-list --count ${{ github.ref_name }} > __build__/ccnt.txt
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tc-api
          path: functions/that-api-ical-generator/__build__
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'

  deploy-image:
    name: Deploy that-api-ical-generator
    needs: build
    runs-on: ubuntu-22.04
    env:
      apiName: ical-generator
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: tc-api
          path: __build__

      - name: Setup google auth for github actions
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Setup GCLOUD CLI Action
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "437.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: gcloud docker cred helper
        run: gcloud auth configure-docker
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Build Docker image
        run: |
          cp __build__/Dockerfile ./ && rm __build__/Dockerfile
          docker build . --tag us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.apiName }}
      - name: Publish image to gcp
        run: docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.apiName }}
      - name: Deploy to Cloud Run
        run: |
          gcloud secrets versions access latest --secret any-secrets2array-util_file > secrets2array.sh && chmod +x secrets2array.sh
          GCR_ENV_VARS=$(gcloud secrets versions access latest --secret prod-api-ical-generator-env | ./secrets2array.sh)
          C_CNT=$(cat __build__/ccnt.txt)
          SENTRYREL=SENTRY_VERSION=that-api-${{ env.apiName }}@$(cat __build__/package.json | jq '.version' | tr -d '"')-$C_CNT.$(echo $GITHUB_SHA | cut -c1-7)
          GCR_ENV_VARS="${GCR_ENV_VARS}, ${SENTRYREL}"
          gcloud run deploy ${{ env.apiName }} --image us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.apiName }} --region=us-central1 --platform=managed --allow-unauthenticated --set-env-vars="$GCR_ENV_VARS" --timeout=30 --memory=256Mi --cpu=1 --min-instances=0
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
