# Validate lint, build, and tests on PR
name: that-api-webhooks Pull Request

# disabled on 8/27/2020
on:
  pull_request:
    paths:
      - "functions/that-api-webhooks/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm ci, run
        run: |
          cd functions/that-api-webhooks
          cp .env.sample .env
          npm ci
          npm run lint
          npm run test
        env:
          CI: true
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: PullReq CI Webhooks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
