# Validate lint, build, and tests on PR
name: that-api-webhooks Pull Request

on:
  pull_request:
    paths:
      - 'functions/that-api-webhooks/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: npm ci, run
        run: |
          cd functions/that-api-webhooks
          cp .env.sample .env
          npm ci
          npm run lint
          npm run test
