name: tickle-bot Pull Request

on:
  pull_request:
    paths:
      - "functions/tickle-bot/**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci, run validate
        run: |
          cd functions/tickle-bot
          pwd
          cp ./.env.sample .env
          npm ci
          npm run validate
        env:
          CI: true
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: PullReq CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
