# Validate lint, build, and tests on PR
name: voting-on-delete Push Master

on:
  push:
    branches:
      - master
    paths:
      - "functions/voting-on-delete/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: npm ci, lint, test
        run: |
          cd functions/voting-on-delete
          cp .env.sample .env
          npm ci
          npm run validate
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup GCP Deploy Function - voting-on-delete
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "274.0.1"
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Load gcloud beta bits
        run: gcloud components install beta
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: write .env file
        run: |
          cd functions/voting-on-delete
          gcloud beta secrets versions access latest --secret prod-voting-on-delete-env > .env
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Run GCP Deploy Function - voting-on-dete
        run: |
          cd functions/voting-on-delete
          gcloud functions deploy voting-on-delete --runtime nodejs10 --trigger-event providers/cloud.firestore/eventTypes/document.delete --trigger-resource "projects/all-that/databases/(default)/documents/votes/{vote}" --entry-point handler
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
